package farmer.game;

public enum RollResult {

    NEW_ANIMAL_CAME_TO_THE_WORLD,
    NEW_ANIMAL_CAME_TO_THE_WORLD_TWICE,
    NEW_ANIMALS_CAME_TO_THE_WORLD,
    WOLF_KILLED_ANIMALS,
    WOLF_KILLED_ANIMALS_AND_NEW_RABBIT_CAME_TO_THE_WORLD,
    FOX_KILLED_RABBITS,
    FOX_KILLED_RABBITS_AND_NEW_ANIMAL_CAME_TO_THE_WORLD,
    WOLF_AND_FOX_KILLED_ANIMALS,
    NO_CHANGES_ON_THE_FARM
}
